.\" Copyright (C) 2019 VirtualSquare. Project Leader: Renzo Davoli
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License,
.\" as published by the Free Software Foundation, either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
.\" MA 02110-1301 USA.
.\"
.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "RANDMAC" "1" "July 2020" "VirtualSquare"
.SH "NAME"
\fBrandmac\fR \- generate random MAC addresses
.SH "SYNOPSIS"
\fBrandmac\fR [\fIoptions\fR]
.SH "DESCRIPTION"
\fBrandmac\fR print a random MAC address\. This utility has been designed to give random MAC addresses to interfaces of virtual machines\.
.SH "OPTIONS"
.TP
\fB\-l\fR, \fB\-\-local\fR
Generate a local administered MAC\.
.TP
\fB\-g\fR, \fB\-\-global\fR
Generate a global unique MAC\.
.TP
\fB\-u\fR, \fB\-\-unicast\fR
Generate a MAC for unicast\.
.TP
\fB\-m\fR, \fB\-\-multicast\fR
Generate a MAC for multicast\.
.TP
\fB\-U\fR, \fB\-\-uppercase\fR
Print uppercase hex digits\.
.TP
\fB\-e\fR, \fB\-\-eui64\fR
Generate an EUI64 address\.
.TP
\fB\-o\fR \fIoui_addr\fR, \fB\-\-oui\fR \fIoui_addr\fR
Set the Organizationally Unique Identifier (OUI)\.
.TP
\fB\-v\fR \fIvendor\fR, \fB\-\-vendor\fR \fIvendor\fR
Set the OUI of a specific vendor\.
.TP
\fB\-q\fR, \fB\-\-qemu\fR
Set the standard OUI of qemu/kvm\.
.TP
\fB\-x\fR, \fB\-\-xen\fR
Set the standard OUI of xen\.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display a short help message and exit\.
.SH "EXAMPLE"
Start a kvm VM using a random generated MAC address (while preserving the standard qemu\'s OUI)
.IP "" 4
.nf
$ qemu\-system\-x86_64 \-accel kvm \|\.\|\.\|\. \e
    \-device e1000,netdev=vde0,mac=`randmac \-q` \e
    \-netdev vde,id=vde0,sock=vde://
.fi
.IP "" 0
.SH "SEE ALSO"
qemu(1)
.SH "AUTHOR"
VirtualSquare\. Project leader: Renzo Davoli\.
